/**
 * sandbox.ts — Sandboxed JavaScript execution for the spreadsheet query agent.
 *
 * Security model:
 *  - Code runs inside Node.js `vm.runInNewContext()` with a whitelist-only global scope.
 *  - NO `require`, `process`, `fs`, `fetch`, `eval`, `Function` constructor.
 *  - Only pure data-manipulation globals: Math, JSON, Array, Object, Date, String, Number, etc.
 *  - 5-second execution timeout kills infinite loops.
 *
 * Limitations (documented for production hardening):
 *  - `vm.runInNewContext` provides *context isolation*, not a true security sandbox.
 *    A determined attacker could escape via prototype pollution or constructor chains.
 *  - For production, consider `isolated-vm` (V8 isolate) or a Worker thread.
 *  - For this hackathon demo, the threat model is "LLM-generated code that may be
 *    buggy but not intentionally malicious," which vm context isolation handles well.
 */

import vm from 'vm';
import { SCI } from './scientific-formulas';

export interface SandboxResult {
  success: boolean;
  result: unknown;
  error?: string;
  executionTimeMs: number;
  /** The code that was executed (for the trust/transparency layer) */
  code: string;
}

/** Max execution time in milliseconds (increased for scientific computations) */
const EXECUTION_TIMEOUT_MS = 15000;

/** Max result JSON size (prevent memory bombs) */
const MAX_RESULT_SIZE = 2 * 1024 * 1024; // 2 MB

/**
 * Execute LLM-generated JavaScript code in a sandboxed context.
 *
 * The code receives a `data` variable (array of row objects) and must
 * assign its answer to a `result` variable.
 *
 * @param code   - JavaScript code string generated by the LLM
 * @param data   - Array of row objects from the spreadsheet
 * @param timeout - Execution timeout in ms (default 5000)
 * @returns SandboxResult with the computed value or an error message
 */
export function executeSandboxed(
  code: string,
  data: Record<string, unknown>[],
  timeout: number = EXECUTION_TIMEOUT_MS,
  extraGlobals?: Record<string, unknown>,
): SandboxResult {
  const startTime = Date.now();

  // Validate inputs
  if (!code || typeof code !== 'string') {
    return {
      success: false,
      result: null,
      error: 'No code provided for execution.',
      executionTimeMs: 0,
      code: code || '',
    };
  }

  if (!Array.isArray(data)) {
    return {
      success: false,
      result: null,
      error: 'Data must be an array of row objects.',
      executionTimeMs: 0,
      code,
    };
  }

  try {
    // Build the sandbox context with ONLY safe globals
    const sandbox: Record<string, unknown> = {
      // The dataset
      data: Object.freeze(data.map((row) => ({ ...row }))), // shallow-freeze rows

      // Result placeholder — code must assign to this
      result: undefined,

      // Safe built-in constructors and functions
      Math,
      JSON: {
        parse: JSON.parse,
        stringify: JSON.stringify,
      },
      Date,
      Number,
      String,
      Boolean,
      Array,
      Object,
      RegExp,
      Map,
      Set,
      parseInt,
      parseFloat,
      isNaN,
      isFinite,
      Infinity,
      NaN,
      undefined,
      null: null,

      // Console for debugging (captured, not printed)
      console: {
        log: () => {},
        warn: () => {},
        error: () => {},
      },

      // Scientific formulas namespace (deterministic, tested implementations)
      SCI,

      // Any extra globals (e.g. allSheets for multi-file dataset analysis)
      ...(extraGlobals || {}),
    };

    // Create an isolated context
    const context = vm.createContext(sandbox, {
      name: 'spreadsheet-sandbox',
      codeGeneration: {
        strings: false,  // Disallow eval() and new Function()
        wasm: false,     // Disallow WebAssembly compilation
      },
    });

    // Execute the code with a timeout
    const script = new vm.Script(code, {
      filename: 'query.js',
    });

    script.runInContext(context, { timeout });

    const executionTimeMs = Date.now() - startTime;

    // Extract result
    const result = sandbox.result;

    // Safety: check result size
    try {
      const serialized = JSON.stringify(result);
      if (serialized && serialized.length > MAX_RESULT_SIZE) {
        return {
          success: false,
          result: null,
          error: `Result too large (${(serialized.length / 1024 / 1024).toFixed(1)} MB). Try narrowing your query.`,
          executionTimeMs,
          code,
        };
      }
    } catch {
      // Result is not JSON-serializable — try to convert
      return {
        success: true,
        result: String(result),
        executionTimeMs,
        code,
      };
    }

    return {
      success: true,
      result,
      executionTimeMs,
      code,
    };
  } catch (err: unknown) {
    const executionTimeMs = Date.now() - startTime;

    let errorMessage: string;
    if (err instanceof Error) {
      if (err.message.includes('Script execution timed out')) {
        errorMessage = `Code execution timed out after ${timeout / 1000} seconds. The query may be too complex or caused an infinite loop.`;
      } else {
        errorMessage = err.message;
      }
    } else {
      errorMessage = String(err);
    }

    return {
      success: false,
      result: null,
      error: errorMessage,
      executionTimeMs,
      code,
    };
  }
}
